# Server Configuration
server.port=8080

# Database Configuration (MySQL - Aiven Cloud)
spring.datasource.url=jdbc:mysql://${DB_HOST:mysql-16357880-pachiyammald2016-906f.l.aivencloud.com}:${DB_PORT:10152}/${DB_NAME:defaultdb}?useSSL=true&requireSSL=true&serverTimezone=UTC
spring.datasource.username=${DB_USER:avnadmin}
spring.datasource.password=${DB_PASSWORD:AVNS_vEhU97rFsdvqR1oN_MJ}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Spring Logging
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG

# SMTP Mail Configuration for sending real Email OTP (Leave username blank to print code in backend console only)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:pachiyammald2016@gmail.com}
spring.mail.password=${MAIL_PASSWORD:iffmjagkarskylke}
spring.mail.properties.mail.transport.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


